server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: Employee_Management
  datasource:
    url: jdbc:postgresql://localhost:5432/employee_management
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  sql:
    init:
      mode: always
      platform: postgresql
      # Location of schema.sql and data.sql files
      schema-locations: classpath:schema.sql
      #data-locations: data.sql

logging:
  level:
    org.springframework.boot.sql.init: DEBUG