server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: Employee_Management
  datasource:
    url: jdbc:postgresql://localhost:5432/employee_management
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

